# Generated by Django 4.1.1 on 2022-09-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="dislikes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="likes",
            field=models.BooleanField(default=False),
        ),
    ]
