# Generated by Django 4.1.1 on 2022-09-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_dislikes_alter_job_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
