# Generated by Django 4.1.1 on 2022-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("entry level", "E"),
                    ("mid level", "M"),
                    ("senior level", "S"),
                ],
                default="entry level",
                max_length=12,
            ),
        ),
    ]
