# Generated by Django 4.1.1 on 2022-10-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_skill_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_level", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="skill_level",
            field=models.ForeignKey(
                default="entry level",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="jobs.skilllevel",
            ),
        ),
    ]
