# Generated by Django 4.1.2 on 2022-10-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_skilllevel_alter_job_skill_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="skill_level",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="jobs.skilllevel",
            ),
        ),
    ]
