# Generated by Django 4.1.1 on 2022-09-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                help_text="<em><a target='_blank' href='https://stluciapostal.com/postal-codes-2/'>Post Codes</a></em>",
                max_length=8,
            ),
        ),
    ]
