# Generated by Django 4.1.2 on 2022-10-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_course_relationship_otherdetails_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="course1",
        ),
        migrations.RemoveField(
            model_name="education",
            name="course2",
        ),
        migrations.RemoveField(
            model_name="education",
            name="course3",
        ),
        migrations.RemoveField(
            model_name="education",
            name="course4",
        ),
        migrations.AddField(
            model_name="education",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="course",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
