# Generated by Django 4.1.2 on 2022-10-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "providers",
            "0006_shift_workschedule_workinterest_other_commitments_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OtherDetails",
            new_name="OtherDetail",
        ),
    ]
