# Generated by Django 4.1.2 on 2022-10-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0008_vaccination_immunisationstatement"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="b_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccination",
            name="i_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
