# Generated by Django 4.1.2 on 2022-10-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0009_vaccination_b_date_vaccination_i_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccination",
            name="b_date",
            field=models.DateField(blank=True, null=True, verbose_name="booster due"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="i_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="injection date"
            ),
        ),
    ]
